### ISSUE TITLE
command command doesnt work

### ISSUE THREAD

**Issue by ghost** [RubiksImplosion/Minecraft-TAS#11]
the command "command" isnt working and i cant figure out how to use it can you help??

**Comment by RubiksImplosion** [comment]
"+command" pushes the command key (default "/"), and "-command" releases the command key. However raw text input isn't implemented yet so opening the command menu doesn't actually let you do a whole lot and may be buggy.

**Comment by ghost** [comment]
can you give me an example on how to make a script using command doing "/setblock ~ ~ ~ end_portal

**Comment by RubiksImplosion** [comment]
Unfortunately the ability to type out text is not implemented yet so having a script execute commands is not currently possible. This is very high on the list of priorities for features to implement though and will be implemented next update most likely.

**Comment by ghost** [comment]
oh, can I use the chat command to do a command in Minecraft?

**Comment by RubiksImplosion** [comment]
It will open the chat, but there is no way to automatically type in characters to the chat window

**Comment by ghost** [comment]
Okay, thanks for the help.
