### ISSUE TITLE
Little mildly annoying issue

### ISSUE THREAD

**Issue by DarkblooM-IO** [RubiksImplosion/Minecraft-TAS#8]
Hey!

First of all thank you for creating this mod, I have been looking forward to script-based Minecraft TASing for so long and finally seeing it makes me really happy :)

The only issue I have is not so big of a deal but I've noticed: when I run one same script multiple times in a row, it does not always give the exact same result.

For exemple, if I want to run towards a tree, break the base, then walk forward a bit to break the rest of the wood, sometimes it works fine and sometimes it won't walk for long enough and start breaking the leaves instead.

Do you think you could fix it?

Again, this is not a huge problem and the mod works just fine anyway, I just wanted to report this.

Thanks

**Comment by RubiksImplosion** [comment]
Funny you should mention this, the task I am currently working on is synchronizing the client with the integrated server. I will try to finish it and put a release out later today.

**Comment by DarkblooM-IO** [comment]
Also, when you send a _slot_ input but you're not in an inventory, the game crashes
