### ISSUE TITLE
Only works with setup commands

### ISSUE THREAD

**Issue by Vlogcks** [RubiksImplosion/Minecraft-TAS#9]
For some reason it only works with the setup scripts, When i try +forward; sprintwait 40-sprint; -forward it doesnt work, HOWEVER when i copy and paste it from the other script files it works, So i cant use yaw or pitch because when I edit it it doesnt work but when it comes from a other script or the setup ones

**Comment by RubiksImplosion** [comment]
Is there any error message that pops up?

**Comment by DarkblooM-IO** [comment]
I'd put my finger on typos for this

**Comment by Vlogcks** [comment]
> Is there any error message that pops up?

Sorry For Late Reply and No There Is No Error Message It Just Doesnt Work When I Start The Script File

**Comment by RubiksImplosion** [comment]
Can you send the contents of the script that is giving you trouble?

**Comment by Vlogcks** [comment]
yaw and pitch

**Comment by RubiksImplosion** [comment]
I mean the exact contents of the file, copy and paste them

**Comment by Vlogcks** [comment]
Ohh alr just hold on

**Comment by Vlogcks** [comment]
+forward; +sprintwait 40 -forward; -sprint yaw 45pitch 5; +forward; +sprint; +jump

**Comment by RubiksImplosion** [comment]
Is this all on one single line? Or was it compressed by github

**Comment by Vlogcks** [comment]
a single line

**Comment by RubiksImplosion** [comment]
The TAS will execute one line per tick, so if the entire command is on one line it will execute every single command in one tick
The correct format for this script is this (assuming line breaks occur where there are missing semicolons)
+forward; +sprint
wait 40
-forward; -sprint
yaw 45
pitch 5; +forward; +sprint; +jump

**Comment by Vlogcks** [comment]
Ok hold on let me try this

**Comment by Vlogcks** [comment]
wait where do i find fabricapi 1.16.3?

**Comment by Vlogcks** [comment]
Nevermind

**Comment by Vlogcks** [comment]
Wait now when i load up the mod i cant see the script file in .minecraft

**Comment by RubiksImplosion** [comment]
Is your script a .script file or a .script.txt file?

![image](https://user-images.githubusercontent.com/39072130/155657811-63a76412-4c68-434f-a32c-9ca688e85695.png)
Click this to check and make sure it is just .script

**Comment by Vlogcks** [comment]
![unknown](https://user-images.githubusercontent.com/97580380/155657981-92495d14-c766-4701-9240-3d861a36a821.PNG)
No its not that its that the script folder where i type the scripts hasnt generated

**Comment by RubiksImplosion** [comment]
Oh in that case you can just make the folder yourself

**Comment by Vlogcks** [comment]
Oh

**Comment by Vlogcks** [comment]
Another problem (Sorry Much) The pitch and yaw dont set, When the script finishes and i move the cursor, Then the pitch and yaw will change

**Comment by RubiksImplosion** [comment]
Yes this is a known bug that I will fix eventually. Due to the nature of how mouse movement is implemented it is a bit tricky to fix.

**Comment by Vlogcks** [comment]
Oh thanks

**Comment by Vlogcks** [comment]
Also Um (Sorry Again) The yaw command more of like Adds 45 yaw more than set the yaw to 45

**Comment by RubiksImplosion** [comment]
It does? If you press F3 and rerun the script, the yaw should be set to 45 no matter your original facing angle.

**Comment by Vlogcks** [comment]
Yes I did look at F3
Apparently it went from -31 82 to -76 5

**Comment by RubiksImplosion** [comment]
What version of the mod are you using? Since i think i fixed this issue in the most recent release.

**Comment by Vlogcks** [comment]
1.16.3

**Comment by RubiksImplosion** [comment]
I fixed the issue with yaw in the most recent version, but a hack-fix you can do is to insert two copies of the yaw command like so:
+forward; +sprint
wait 40
-forward; -sprint
yaw 45
yaw 45
pitch 5; +forward; +sprint; +jump

**Comment by Vlogcks** [comment]
HOLY MOLY TYSM

**Comment by Vlogcks** [comment]
1 last question tho? (sorry) Tell me if you have time I wont bother u if u dont

**Comment by RubiksImplosion** [comment]
When asking a question online it is better to just ask the question rather than ask permission to ask the question. So go ahead and ask your question

**Comment by Vlogcks** [comment]
How do i change a slot in my inventory?
Like Theres a iron sword in my inventory and i will place it in my 1st hotbar slot How will i do it?

**Comment by RubiksImplosion** [comment]
Inventory TASing is only available in version 0,4.1 and above. I recommend updating to the most recent release 0.4.2 in order to use inventory TASing. There are example scripts for inventory TASing here https://github.com/RubiksImplosion/Minecraft-TAS/tree/master/run/scripts

**Comment by Vlogcks** [comment]
Ohh

**Comment by Vlogcks** [comment]
all it did was open my inventory and close it

**Comment by RubiksImplosion** [comment]
What script did you use?

**Comment by Vlogcks** [comment]
InventoryTestScript

**Comment by RubiksImplosion** [comment]
With version 0.4.2 for 1.17.1?

**Comment by Vlogcks** [comment]
Oh Um wait nvm false alert im going to download that version

**Comment by RubiksImplosion** [comment]
inventoryTestScript also assumes you have a stack of logs in the first slot of your hotbar, since it crafts and places down a crafting table.

**Comment by Vlogcks** [comment]
wow

**Comment by Vlogcks** [comment]
You put alot of effort into this mod

**Comment by Vlogcks** [comment]
thanks alot

**Comment by RubiksImplosion** [comment]
Thank you for your compliment
